### ISSUE TITLE
Test Debug Session still proceeds after cancelling build task

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1001]
**Describe the bug**
When you cancel the build task that precedes a debug session for a test, the debug session still starts and LLDB can show fatal errors

**To Reproduce**
1. I had cleared .build
2. Started debug session for a test
3. Pressed ctrl+c in the task terminal to cancel the build all task when I realized I forgot to save a file
4. Build task is cancelled, but debug session still starts
5. The call stack frame showed a fatal error

**Expected behavior**
Check the exit code, if non-zero then don't proceed?

**Environment**
 - OS: macOS
 - Swift version (output of `swift --version`): 6.0
 - Visual Studio Code version: 1.92
 - vscode-swift version: 1.10.7

**Additional context**
N/A

**Comment by matthewbastien** [comment]
Verified with e0a0fba
