### ISSUE TITLE
VS Code does not show diagnostics for C files

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#1028]
When opening a C file using VS Code with SourceKit-LSP as the language server, no diagnostics are shown. This seems to be because the diagnostic’s source is `clang` and that’s not in `DiagnosticsManager.sourcekit`. Since we forward the diagnostic’s source from clangd here, I wonder whether it would be possible to generalize the implementation of `DiagnosticsManager` to consider everything that’s not from `swiftc` as a SourceKit diagnostics.

I think build errors from C files in a SwiftPM package also don’t show up in the Problems view.

**Comment by plemarquand** [comment]
Verified with 2cd60ca0c11d1604db33a21e9940e3bfc55b46e8
