### ISSUE TITLE
While tests are running, class and target TestItems are not updated

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#1029]
**Describe the bug**
While tests are running, suite/XCTestCase class and target TestItems are not updated. They are only updated once the test run has finished. If you have a lot of tests this makes it hard to see progress.

**To Reproduce**
1. Open SwiftPM project with large number of tests
2. Go to TestExplorer
3. Expand TestItems so you only see list of classes
4. Run tests

**Expected behavior**
As each suite/XCTestCase class has all its tests completed its TestItem updated accordingly

The extension used to do this. @plemarquand I seem to remember seeing you removed the code that did this with a comment about it being unnecessary. I should have verified this but didn't.

**Comment by plemarquand** [comment]
@adam-fowler I don't think I'm reproducing this correctly. The Target and Suite show the spinner as long as there are tests executing within them, but this behaviour is consistent across VS Code Swift extension releases. 

To test I went back to the 1.9 release and recorded an async XCTest Run:

https://github.com/user-attachments/assets/37dd962d-b0e3-4771-89b3-f196e974f808

And then compared it to the same run on `main`. 

https://github.com/user-attachments/assets/2e56ce96-9dc2-426e-a11e-663d1bf70df5

Perhaps VS Code has changed the underlying Test Explorer behaviour?

**Comment by adam-fowler** [comment]
@plemarquand You need a project with multiple suites. The problem is once a suite has completed the test item for that suite is not updated. You'll only see this if you have multiple suites as everything is updated once the all the tests have finished. In the video below notice how the cookie tests are all completed but the CookieTests suite test item is not updated. It gets updated once all tests are complete, but I'd like to see it updated as the tests run.

https://github.com/user-attachments/assets/e1c3f6a6-73da-43b1-b4a7-aee9f2a6e1aa

**Comment by plemarquand** [comment]
Ah! Understood, thanks for the clarification. I'll take a look at this.

**Comment by matthewbastien** [comment]
Verified with d6c91dd
