### ISSUE TITLE
Add protocol stubs with quick fix

### ISSUE THREAD

**Issue by ras0q** [swiftlang/vscode-swift#1030]
**Is your feature request related to a problem? Please describe.**
When a struct does not confirm to protocol, sourcekitd make a warning with "do you want to add protocol stubs?" message , but you need to add stubs manually as the command does not appear in Quick Fix. Is this really an issue of this repository?

**Describe the solution you'd like**
You can automatically add stubs from Quick Fix menu.

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/0ca07368-aceb-497b-b007-c28b3c69cc87)

**Comment by plemarquand** [comment]
@ras0q What Swift version are you using? As of at least Swift 6, I have a "Add stubs for conformance" quick fix menu item. 

<img width="441" alt="Screenshot 2024-08-26 at 8 58 58 AM" src="https://github.com/user-attachments/assets/b23924aa-3d73-4551-aea3-b96839fc2d56">

**Comment by ras0q** [comment]
I was using Swift 5.9.
I see tha it will be supported starting with Swift 6
