### ISSUE TITLE
Not filtering test cases when run multiple times

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1033]
**Describe the bug**
When have a filter applied, all tests for a suite are run (not just filtered ones) when Running until failure or Running multiple times

**To Reproduce**
If I filter by some tag and simply run the test, it only runs the filtered out ones, same as if debugging the test(s). If I run multiple times or to failure on an individual test it is fine, but if I run it on a whole suite, they all run not just the filtered ones
![screenshot_2024-08-27_at_1 46 14___pm_720](https://github.com/user-attachments/assets/365050f6-be64-436f-aa96-0a304f6f923a)

This one you can see ran 5 times
![screenshot_2024-08-27_at_1 48 55___pm_480](https://github.com/user-attachments/assets/e8ca2073-93b6-4a69-ad6f-d6bbb0b58775)

**Expected behavior**
Should only run the tests that satisfy the filter multiple times.

**Environment**
 - OS: macOS
 - Swift version (output of `swift --version`): 6.0
 - Visual Studio Code version: 1.92.2
 - vscode-swift version: 1.10.7

**Additional context**
N/A

**Comment by award999** [comment]
Looks like a vscode limitation. Context menu commands works different than run and debug buttons

**Comment by plemarquand** [comment]
Unfortunately the callback called when you select a menu item on a Test Explorer test item just receives the test item as an argument, not a `vscode.TestRunRequest`. 

`vscode.TestRunRequest`s respect the Test Explorer's filter and can contain multiple test items, while the callback only receives the single right clicked test item and we manually have to create a `vscode.TestRunRequest` from that, without knowledge of the filtered state of the Test Explorer.
