### ISSUE TITLE
Warning and error messages are truncated in Problems view

### ISSUE THREAD

**Issue by HeMet** [swiftlang/vscode-swift#1074]
**Describe the bug**
Warning and error messages are truncated in Problems view
![swift_messages_truncated](https://github.com/user-attachments/assets/0cb36d29-5246-4215-829a-0d95c9ccadcc)

**To Reproduce**
1. Build any project with long enough warnings

**Expected behavior**
Warning messages should not be truncated.

**Environment**
- Swift version 6.0 (swift-6.0-RELEASE)
  Target: x86_64-unknown-windows-msvc
 - Visual Studio Code version: Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
 - vscode-swift version: v1.11.0

**Additional context**

**Comment by plemarquand** [comment]
Verified with 2dad6d7f37e5f9f9547979ee7c39a71c07c73e87
