### ISSUE TITLE
`npm run package` is including unnecessary files

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#1078]
The package scripts now lists all the files being added to the vsix. Not all of these need adding to the extension eg the docs folder
```
swift-lang-1.11.1.vsix
├─ [Content_Types].xml
├─ extension.vsixmanifest
└─ extension/
   ├─ .mailmap
   ├─ .nvmrc
   ├─ .vscode-test.js
   ├─ CHANGELOG.md
   ├─ CONTRIBUTORS.txt
   ├─ LICENSE.txt
   ├─ NOTICE.txt
   ├─ README.md
   ├─ icon.png
   ├─ package.json
   ├─ .devcontainer/
   │  ├─ Dockerfile
   │  └─ devcontainer.json
   ├─ assets/
   │  └─ icon-font.woff
   ├─ dist/
   │  └─ extension.js
   ├─ docs/
   │  ├─ remote-dev.md
   │  ├─ settings.md
   │  ├─ test-coverage.md
   │  ├─ contributor/ (1 file)
   │  └─ images/ (3 files)
   ├─ images/
   │  ├─ install-extension.png
   │  ├─ package-dependencies.png
   │  └─ test-explorer.png
   └─ snippets/
      ├─ swift-testing.code-snippets
      ├─ swift.code-snippets
      └─ xctest.code-snippets
```

**Comment by award999** [comment]
@michael-weng can you verify this?

**Comment by michael-weng** [comment]
Verified:
commit 737ad6941ad7d147f2b3f2f05a5399c618bfa9ad

Files included in the VSIX properly reflects change of PR:
swift-lang-1.11.2.vsix
├─ [Content_Types].xml
├─ extension.vsixmanifest
└─ extension/
   ├─ CHANGELOG.md
   ├─ LICENSE.txt
   ├─ NOTICE.txt
   ├─ README.md
   ├─ icon.png
   ├─ package.json
   ├─ assets/
   │  └─ icon-font.woff
   ├─ dist/
   │  └─ extension.js
   ├─ images/
   │  ├─ install-extension.png
   │  ├─ package-dependencies.png
   │  └─ test-explorer.png
   └─ snippets/
      ├─ swift-testing.code-snippets
      ├─ swift.code-snippets
      └─ xctest.code-snippets
      
Tested with Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
build and debug of test package is working, condition:
swift.debugger.useDebugAdapterFromToolchain needs to be checked
