### ISSUE TITLE
Running a single XCTest tests runs all other tests that have the same prefix

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#1084]
If I have a project with the following test file

```swift
import XCTest

class MyTests: XCTestCase {
    func testFoo() {
        print("foo")
    }

    func testFooBar() {
        XCTFail()
    }
}
```

And I run `testFoo`, then it also runs `testFooBar`. The test repot shows `testFoo` as succeeded and `MyTests` as failed but doesn’t show that `testFooBar` also ran.

**Comment by award999** [comment]
Verified with 2cd60ca0c11d1604db33a21e9940e3bfc55b46e8
