### ISSUE TITLE
Windows regression in 1.11.2: Toolchain fails to be discovered if `SWIFT_TESTING_VERSION` is absent

### ISSUE THREAD

**Issue by z2oh** [swiftlang/vscode-swift#1096]
When using a toolchain version that doesn't have `SWIFT_TESTING_VERSION` in `Info.plist`, an error is thrown which prevents the Swift toolchain from being detected entirely. This is a regression in v.1.11.2.

```
SwiftToolchain.getWindowsPlatformDLLPath (c:\workspace\vscode-swift\src\toolchain\toolchain.ts:757)
getSwiftTestingPath (c:\workspace\vscode-swift\src\toolchain\toolchain.ts:673)
create (c:\workspace\vscode-swift\src\toolchain\toolchain.ts:134)
activate (c:\workspace\vscode-swift\src\extension.ts:67)
```

Changing this line to simply emit a warning and then return `undefined` fixes the issue:
https://github.com/swiftlang/vscode-swift/blob/83fdec066d32f19513ede08bb64723bad8b270f4/src/toolchain/toolchain.ts#L757

Although I'm not sure if there's some more sophisticated mechanism that would be preferred here.

**Environment**
 - OS: Windows 11
 - Swift version (output of `swift --version`):
```
compnerd.org Swift version 6.0-dev (LLVM a527f49f462b0d7, Swift eef85a7be270421)
Target: x86_64-unknown-windows-msvc
```
 - Visual Studio Code version: 1.93.1
 - vscode-swift version: 1.11.2

**Comment by compnerd** [comment]
I think that retaining the error and catching it at the site and logging is a better solution so that other users can require that it is found.

**Comment by plemarquand** [comment]
@z2oh Is this an older Windows toolchain? Can you check the contents of `C:\Users\<USERNAME>\AppData\Local\Programs\Swift\Platforms\6.0.0\Windows.platform\Info.plist` and paste it here?

I agree this should be updated to just log and return `undefined`, but I'm trying to understand why the `SWIFT_TESTING_VERSION` key is missing from the plist.

**Comment by z2oh** [comment]
Yes, I'm using an older toolchain. My `Info.plist` is located in `C:\Users\<USERNAME>\AppData\Local\Programs\Swift\Platforms\0.0.0\Windows.platform` and its contents are:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DefaultProperties</key>
	<dict>
		<key>SWIFTC_FLAGS</key>
		<array>
			<string>-use-ld=lld</string>
		</array>
		<key>XCTEST_VERSION</key>
		<string>development</string>
	</dict>
</dict>
</plist>
```

The specific toolchain release I'm using is here: https://github.com/thebrowsercompany/swift-build/releases/tag/20240626.3

**Comment by plemarquand** [comment]
@z2oh ok, thanks, I think its safe to return `undefined` then as if that key is missing then swift-testing is not present in the toolchain.

**Comment by z2oh** [comment]
Thank you for the quick turnaround!

**Comment by matthewbastien** [comment]
Verified with 0d3185f
