### ISSUE TITLE
Cannot debug single XCTest in 1.11.2

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#1097]
Trying to debug just the `testFoo` test in the following example executes no tests.

```swift
import XCTest

class MyTests: XCTestCase {
    func testFoo() {
        print("x")
    }
}
```

This was working on 1.11.1. I assume this issue was caused by https://github.com/swiftlang/vscode-swift/pull/1086.

**Comment by matthewbastien** [comment]
Verified with 0d3185f
