### ISSUE TITLE
XCTest output is not recorded when using CodeLLDB

### ISSUE THREAD

**Issue by plemarquand** [swiftlang/vscode-swift#1100]
**Describe the bug**
When using CodeLLDB as the debug adapter XCTest output is not captured and so test results are not recorded. If `swift.debugger.useDebugAdapterFromToolchain` is true then output is captured and tests work as expected.

**To Reproduce**
Create a simple XCTest:

```swift
import XCTest

class MyTests: XCTestCase {
    func testFoo() {
        print("x")
    }
}
```

- Right click `testFoo()`'s test icon, Debug Test
- Notice there is Debug Console output for the test, but the test is not marked as passed.

**Environment**
 - OS: macOS
 - Swift version: swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.11 clang-1600.0.26.2)
 - vscode-swift version: 1.11.2

**Comment by michael-weng** [comment]
I will verify this one.

**Comment by michael-weng** [comment]
Verified with and without the patch, the bug is fixed with the patch applied.
