### ISSUE TITLE
Unable to Run Unit Tests

### ISSUE THREAD

**Issue by leogdion** [swiftlang/vscode-swift#1108]
**Describe the bug**
Opening a library-only Package - starting unit tests fails:
https://github.com/brightdigit/IPSWDownloads/tree/v1.0.0-beta.5-devcontainer

**To Reproduce**
1. Open in VS Code
2. Open in Dev Container
3. Run Tests
4. Error produced - See Movie Attached

**Expected behavior**

**Environment**
 - Swift6.0-Noble
 - Visual Studio Code version:
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (2 wks ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

https://github.com/user-attachments/assets/a64a57cd-1384-4ebf-9583-681e73952825

**Comment by plemarquand** [comment]
Thanks for the report. Could you try and run the tests again and then attach the results of `> Swift: Capture VS Code Diagnostic Bundle`. You can use Capture Minimal Diagnostics.

**Comment by leogdion** [comment]
I haven't run into this again. Feel free to close it.
