### ISSUE TITLE
Parses C++ diagnostics test is flaky

### ISSUE THREAD

**Issue by matthewbastien** [swiftlang/vscode-swift#1120]
The DiagnosticsManager integration test `Parses C++ diagnostics` has been flaky lately and failing on pull requests that don't touch the parsing logic.

```
11:57:11   1 failing
11:57:11   1) DiagnosticsManager Test Suite
11:57:11        Parse diagnostics
11:57:11          Parse from task output
11:57:11            Parses C++ diagnostics:
11:57:11      TypeError: Cannot read properties of undefined (reading '0')
11:57:11   	at Context.<anonymous> (out/test/integration-tests/DiagnosticsManager.test.js:191:59)
```

**Comment by award999** [comment]
thanks Matt. To confirm this is just 5.6?

interesting it is the related information that isn't parsed

**Comment by matthewbastien** [comment]
The most recent failure is in #1119 on the Swift 5.6 CI job. I don't know if it only happens on 5.6.

**Comment by matthewbastien** [comment]
Dunno how long this link will stay active for, but here's the actual jenkins job run https://ci.swiftserver.group/job/swift-vscode-swift56-prb/1312/

**Comment by award999** [comment]
@plemarquand this was the one you fixed I believe?

**Comment by plemarquand** [comment]
@award999 @matthewbastien Yes I disabled these on 5.6 in https://github.com/swiftlang/vscode-swift/pull/1127. There is a bug on 5.6 where the wrong line terminal output is cleared by the build progress status.
