### ISSUE TITLE
Failure to identify symbols in Swift workspace/project

### ISSUE THREAD

**Issue by uripre** [swiftlang/vscode-swift#1138]
**Describe the bug**
Thank you for developing this well needed plugin. 

I encountered a problem where the plugin fails to recognize the symbols in my project, showing errors for all of them. 
In XCode it has no issue whatsoever. 
I could not find a way to configure it. Am I missing it?
Any advice on how to fix this?

Any help would be highly appreciated.

**Environment**
 - OS: MacOS 15.0
 - Swift version (output of `swift --version`) swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2) Target: arm64-apple-macosx15.0
 - Visual Studio Code version: 1.93.1
 - vscode-swift version: 1.11.3

**Comment by 0xTim** [comment]
When you say project do you mean a Swift Package or an Xcode Project?

**Comment by uripre** [comment]
XCode project. It's an iOS app created by XCode.

Its structure is as follows: 
- Project
- > All source files
- Pods
- Project.xcodeproj
- Project.xcworkspace
- Podfile
- Podfile.lock
- .git

**Comment by plemarquand** [comment]
Hi @uripre, unfortunately the extension is not compatible with .xcodeproj style projects. Only Swift Package Manager style projects are supported at this time.

**Comment by uripre** [comment]
Oh, got it. Thank you.
