### ISSUE TITLE
Can no longer cancel running tests

### ISSUE THREAD

**Issue by plemarquand** [swiftlang/vscode-swift#1145]
I wrote a test that accidentally never completed. The only way to halt the test run in VS Code was to restart the editor. We need a way to stop a test run. The little square stop button in the attached screenshot does nothing.

<img width="356" alt="Screenshot 2024-10-17 at 11 44 46 AM" src="https://github.com/user-attachments/assets/8762324e-90b6-456f-aeee-fc844d9895a1">

**Comment by adam-fowler** [comment]
That used to work

**Comment by plemarquand** [comment]
A clarification, the Cancel button in the Test Explorer _does_ work and stops a build/cancels running tests as you'd expect, but the Cancel button in the list panel to the right of the test results output (see screenshot) is the one that does nothing.

**Comment by michael-weng** [comment]
Verified on e7f81c930e752bb049fc7c5fae8e98684bd8b54d that a test can be properly cancelled.
