### ISSUE TITLE
Run/Debug/Coverage buttons appear on swift-testing argument TestItems

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#1147]
**Describe the bug**
Run/Debug/Coverage buttons appear on swift-testing argument TestItems and nothing happens when you click on them

**Expected behavior**
Run/Debug/Coverage buttons do not appear. Although ideally they should be there and run the test with that argument.

**Environment**
 - OS: macOS 15
 - Swift version: 6
 - Visual Studio Code version: 1.94.2
 - vscode-swift version: 1.11.3

**Comment by michael-weng** [comment]
Verified on e7f81c930e752bb049fc7c5fae8e98684bd8b54d 
Snippet below will no longer display Run/Debug/Coverage buttons
```
import Testing

struct Day01Tests {
    @Test(arguments: [1,3,2]) func part1(_ x: Int){}
}
```
