### ISSUE TITLE
Class test items displayed in TestResults display no output

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#1148]
**Describe the bug**
When you select a test item associated with a class in the TestResults pane. It outputs
>  The test case did not report any output. 

**Expected behavior**
It should either display the results for all the tests in that class, or the test item should not be displayed in the TestResults pane.

**Comment by plemarquand** [comment]
Its there to support a single binary test product for projects that contain both XCTest and swift-testing tests. @grynspan knows more details.

More information here: https://github.com/swiftlang/swift-package-manager/pull/7766

**Comment by grynspan** [comment]
Sorry, how can I help?

**Comment by plemarquand** [comment]
I guess I'm wondering about the genesis of the swiftpm-testing-helper. It was created as a test runner for both XCTest and Swift-testing tests so they could rub under the same executable, correct?

**Comment by grynspan** [comment]
Not so much! So, **on Linux and Windows**, the test product is a flat executable and runs directly. SwiftPM emits a `main()` function into the executable that calls into XCTest or into Swift Testing depending on what arguments are passed. There is no helper executable needed.

Now, one of our second-tier goals with Swift Testing was for it to share as much logic as possible across platforms. So on all platforms regardless of what kind of test product is produced, the `main()` function Swift Testing emits into the binary is identical.

However, **on Darwin**, the test product expected by XCTest is a loadable, but not executable, bundle. The `main()` function from such a bundle cannot be directly executed—it's just another exported symbol in a library, after all.

Xcode includes an executable, aptly named `xctest`, that knows how to open these bundles, find XCTest tests, and run them. (There are also other ways to run tests via Xcode but they're not relevant to SwiftPM.) XCTest doesn't use the `main()` function at all! It also doesn't know anything about Swift Testing or how to discover or run its tests.

Enter `swiftpm-testing-helper`: it loads an arbitrary loadable bundle/library, finds its `main()` function, and calls it. It does nothing else. The `main()` function, being emitted into the test product exactly the same for Darwin as for Linux and Windows, takes over and runs Swift Testing tests.

In a perfect world, Darwin would let us make .xctest bundles both loadable _and_ executable, and we wouldn't need the helper, but for other unrelated reasons that would be a terrible and dangerous idea, so them's the breaks.

**Comment by plemarquand** [comment]
I accidentally replied to a comment on #1146 here. Moved discussion over to that issue.

**Comment by michael-weng** [comment]
Verified on e7f81c930e752bb049fc7c5fae8e98684bd8b54d

When I select a test item associated with a class in the TestResults pane
> The test case did not report any output.
is no longer spotted, it now properly displays the test item output.
