### ISSUE TITLE
Migrate to @typescript-eslint 8

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#1169]
To get Dependabot back on we had to disable major updates of @typescript-eslint depdendencies: https://github.com/swiftlang/vscode-swift/pull/1166

We should migrate to version 8. Should discuss if we would like to remove the Dependabot rule or if we believe we always suspect a major ESLint update would cause this issue.

**Comment by michael-weng** [comment]
https://github.com/swiftlang/vscode-swift/actions/runs/12149050931/job/33879420980

Verified latest GH action linting properly with eslint8.
