### ISSUE TITLE
Running tests of a test class that has as many tests as there are test classes in the module will run all tests in the module

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#1183]
If you have a project with the following test file and no other tests and you try to run `MyTests`, then it will run `MyOtherTests` as well. 

```swift
import XCTest

class MyTests: XCTestCase {
  func test1() {}
  func test2() {}
}

class MyOtherTests: XCTestCase {
  func testOther() {}
}
```

I think the bug is that `itemContainingAllArgs` is just checking counts and because there are two tests to run, it thinks that all the tests in the module (or project, not sure about the granularity here) are included, because the module/project also has two children.

https://github.com/swiftlang/vscode-swift/blob/b8e8e1ca23925590543d0b898244a7ff8433f993/src/TestExplorer/TestRunArguments.ts#L125

**Comment by michael-weng** [comment]
Verified on e7f81c930e752bb049fc7c5fae8e98684bd8b54d
Able to run MyTests only in the provided example in the issue.
