### ISSUE TITLE
Integration Tests: Inline/Expand Macro

### ISSUE THREAD

**Issue by michael-weng** [swiftlang/vscode-swift#1205]
Add integration tests that verify macro action integration with Sourcekit-lsp.
- Similar to https://github.com/swiftlang/vscode-swift/issues/1235, ensure the integration with sourcekit-lsp works as intended, with correct requests sent and responses received.
- Detect potential changes in the LSP response for expand macro feature, which requires extra code in the extension to display the code and position in peek view.

**Comment by award999** [comment]
@michael-weng can you add the plan to the description of what will be tested

**Comment by michael-weng** [comment]
> @michael-weng can you add the plan to the description of what will be tested

Done.
