### ISSUE TITLE
Get errors for not finding variables in scope (that are found in Xcode

### ISSUE THREAD

**Issue by nikitavoloboev** [swiftlang/vscode-swift#1221]
**Describe the bug**

In this repo: https://github.com/nikitavoloboev/NotchBar

I get no type errors when I open it in Xcode:

<img width="712" alt="image" src="https://github.com/user-attachments/assets/e8ca410a-f7ef-4f60-9c7f-8ab5206da11d">

But in VSCode and this extension, I see:

![CleanShot 2024-11-23 at 23 59 52@2x](https://github.com/user-attachments/assets/333c8569-c3aa-473b-9558-2208dd37d40c)

Not sure why.

**To Reproduce**

1. clone https://github.com/nikitavoloboev/NotchBar
2. open in vscode and have extension installed
3. open `AppView` on this line https://github.com/nikitavoloboev/NotchBar/blob/main/src/NotchBar/Sources/AppView.swift#L20

You will see error.

**Expected behavior**

No type errors.

**Environment**
 - OS: 15.2
 - Swift version (output of `swift --version`): `swift-driver version: 1.115.1 Apple Swift version 6.0.3 (swiftlang-6.0.3.1.4 clang-1600.0.30) Target: arm64-apple-macosx15.0`
 - Visual Studio Code version: 1.93.1
 - vscode-swift version: `vscode-swift --version` says `command not found`

**Comment by nikitavoloboev** [comment]
Perhaps I need to install `vscode-swift` somehow? I thought it would come as part of extension.

**Comment by plemarquand** [comment]
This project doesn't seem to be a Swift Package Manager based project; it doesn't have a Package.swift. Instead it uses a tool called [Tuist](https://tuist.dev/) to generate an Xcode project.

Unfortunately the vscode-swift extension doesn't support working with Xcode projects at this time, so I'm going to close out the issue, but please leave a comment if you have any questions or suggestions.

**Comment by nikitavoloboev** [comment]
Hey @plemarquand 

Can I kindly ask to look at this simple project: https://github.com/nikitavoloboev/swift-mac-app-test

It does have `Project.swift`, here: https://github.com/nikitavoloboev/swift-mac-app-test/blob/main/Project.swift

But when I open the project in vscode (with vscode-swift extension installed), I get these errors still:

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/6c0e64e3-82f5-402e-a38e-8df59fb01dcc">

Thank you lots.

**Comment by plemarquand** [comment]
@nikitavoloboev Swift Package Manager projects have a **`Package.swift`**, not a `Project.swift`. `Project.swift` seems to be a Tuist concept.

**Comment by coolcorexix** [comment]
> Unfortunately the vscode-swift extension doesn't support working with Xcode projects at this time

@plemarquand this is sad to hear because every Swift projects are supposed to be used with XCode. There is not other alternative way to compile these codes
