### ISSUE TITLE
Problems in Macros should show the original source line

### ISSUE THREAD

**Issue by NinjaLikesCheez** [swiftlang/vscode-swift#1224]
**Describe the bug**
When a diagnostic is issued in a macro expansion, VSCode's 'problem' window will link to the `swift-generated-source`/expanded macro source file and not the source file where the problem happens.

**To Reproduce**
1. Create a new SPM library target
2. In the test file use the `#expect` macro to `try` a non-throwing function
3. A warning (`No calls to throwing functions occur within 'try' expression`) will occur and clicking it will take you to the expanded macro source

**Expected behavior**
When clicking the warning, I'd expect to be taken to the `original-source-range` where the issue occurred.

**Environment**
 - OS: macOS Sequoia 15.1.1
 - Swift version: swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2) Target: arm64-apple-macosx15.0
 - Visual Studio Code version: Version: 1.95.3 (Universal)
 - vscode-swift version: v1.11.3

**Additional context**
```swift
import Testing
@testable import Test

func test() -> Bool {
	return true
}

@Test func example() async throws {
    // Write your test here and use APIs like `#expect(...)` to check expected conditions.
		#expect(try await test())
}
``` is a test case

**Comment by plemarquand** [comment]
@NinjaLikesCheez thanks for the report! I think #1234 should address this issue. It will be shipped in the next release of the extension.

**Comment by award999** [comment]
verified with c047d4e

**Comment by NinjaLikesCheez** [comment]
> @NinjaLikesCheez thanks for the report! I think #1234 should address this issue. It will be shipped in the next release of the extension.

You're amazing - thank you!
