### ISSUE TITLE
"Clean Build" should clean sourcekit-lsp's `.index-build` as well

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/vscode-swift#1248]
**Describe the bug**
"Clean Build" should clean sourcekit-lsp's `.index-build` as well.
It only cleans `.build`.
Not sure if this should be something to change in SwiftPM's command, or something to just be added to this extension.

**To Reproduce**
Simply trigger the "Clean Build Folder" action on VS Code.

**Expected behavior**
`.index-build` should also be cleaned.

**Environment**
Swift 6.0.* release

**Additional context**

**Comment by award999** [comment]
Since this was hidden behind an experimental setting for 6.0, and won't be an issue in 6.1, we're going to close
