### ISSUE TITLE
Jump to definition opens files in .build / .index-build

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/vscode-swift#1279]
**Describe the bug**
Jump to definition opens files in .build / .index-build, which is fine, but the file navigator also shows the file and opens up .index-build.

**To Reproduce**
Jump to definition of something declared in a dependency of a package. 

**Expected behavior**
The Xcode behavior is nicer here, which is to say that it does open the file, but it doesn't touch the file navigator.

**Environment**
 - OS: macOS 15.2
 - Swift version: 6.0.2
 - Visual Studio Code version: VSCode Version: 1.93.1
 - vscode-swift version: 1.11.3

**Additional context**

**Comment by adam-fowler** [comment]
There's a VSCode setting for that. Can't remember what it's called though. Sorry can't be more helpful.

**Comment by plemarquand** [comment]
The setting is `explorer.autoReveal`, but unfortunately it applies globally to the workspace and can't be scoped to `false` for just the .build folder.

I don't think there is much the Swift extension can do here. Since this is a VS Code core behaviour I'm going to close this issue.
