### ISSUE TITLE
Consider adding the ability to run an application in release or debug mode from @main

### ISSUE THREAD

**Issue by fwgreen** [swiftlang/vscode-swift#525]
The Java IDE supports this feature:

![Screenshot 2023-04-18 at 8 36 09 PM](https://user-images.githubusercontent.com/7098161/232936574-e6a797e8-e83a-4317-a44b-ba9eedb9a8c8.png)

Why not Swift?

![Screenshot 2023-04-18 at 8 43 02 PM](https://user-images.githubusercontent.com/7098161/232937126-b10347b9-7ff6-4227-80c7-0a1e03aa49e4.png)

**Comment by adam-fowler** [comment]
Not sure what you mean exactly here. You can run both debug and release via F5. You select which target via the debugger

**Comment by adam-fowler** [comment]
I had a little investigation to see how they implemented this. They use a custom LSP `resolveMainMethod` and setup a CodeLens that uses this command to get position of the main function. As this involves a new custom SourceKit-LSP command I'm not sure this is worth the hassle.

As an aside I have thought of adding context menu entries for running/debugging swift executables. This might make them a little more discoverable.

**Comment by adam-fowler** [comment]
Looks like we might get the sourcekit-lsp support https://github.com/apple/sourcekit-lsp/issues/797

**Comment by plemarquand** [comment]
Support has been added for this in sourcekit-lsp and vscode-swift (https://github.com/swiftlang/vscode-swift/pull/973). Once a new vscode-swift is released you'll need a new sourcekit-lsp to see these code lenses.
