### ISSUE TITLE
Showing Macro Expansion

### ISSUE THREAD

**Issue by filip-sakel** [swiftlang/vscode-swift#564]
**Is your feature request related to a problem? Please describe.**
Without seeing what code macros generate, it's hard to understand macro-related errors. For example, a macro might try to access a variable "_count" but forget the underscore prefix: "count". Being able to see the macro expansion would make it easy to identify the problem, which is critical for developing macros.

**Describe the solution you'd like**
An Xcode-like action could be shown when opening the context menu (when right clicking) on a macro. Then, after finding the expansion, the extension could be shown below the code using the macro (similar to inlay hints). Otherwise, a pop up showing expanded code could appear (similar to when inspecting documentation).

**Describe alternatives you've considered**
The alternative is to use a compiler flag to see macro expansions. That lacks specificity, as all macro expansions are shown. Even if the compiler gains the ability to only show the expansion of one macro, typing that macro's name or source location into the command line can hamper productivity. Instead, it's much more convenient to click on the macro, right in the editor, and be shown its expansion.

**Additional context**
Related SourceKit LSP issue https://github.com/apple/sourcekit-lsp/issues/755

**Comment by adam-fowler** [comment]
As you have seen I've already added an issue for sourcekit-lsp. I've had a look through the VSCode APIs and so far haven't found an easy way to display extra content inside an TextEditor window. I'll need to investigate further.

**Comment by filip-sakel** [comment]
I found [this](https://github.com/microsoft/vscode-cpptools/issues/1734) discussion in the cpp-tools repo, where macro expansions look like so:

![image](https://github.com/swift-server/vscode-swift/assets/51793967/fa8e14b8-407e-4149-bf7a-789f05cc04d6)

**Comment by adam-fowler** [comment]
As an aside there is already a code action "Inline Macro" which will expand the macro into your file. You can use that plus Ctrl+Z to view the macro and revert

**Comment by filip-sakel** [comment]
Thanks! I tried that but no code action showed up :( Are there specific version requirements (for Swift or even VSCode) for this to work?

**Comment by adam-fowler** [comment]
Probably best to install Xcode beta 3. Beta 2 version of sourcekit-lsp had issues.
You click on the macro and a little lightbulb should appear next to it, click on the lightbulb and a series of options are shown including "Inline Macro"
