### ISSUE TITLE
Swiftc-sourced problems should nest their related information

### ISSUE THREAD

**Issue by tristanlabelle** [swiftlang/vscode-swift#570]
Compare `sourcekitd` and `swiftc` for this error. `sourcekitd` has the related information nested, `swiftc` does not.
![unnamed](https://github.com/swift-server/vscode-swift/assets/2314287/56892bda-f83c-4c21-b31b-2af1afc5399c)

**Describe the solution you'd like**
`swiftc`-sourced problems should nest the related information like `sourcekitd`

**Additional context**
It's not super clear whether this is implementable with problems matchers. But maybe the Swift extension could take over handling of the diagnostics and create the nesting (not sure if that is possible).

https://code.visualstudio.com/docs/editor/tasks#_defining-a-multiline-problem-matcher

**Comment by adam-fowler** [comment]
I've had a look into this and the problem marchers don't look like they are flexible enough to do this. 

I'll ask in the vscode repository

**Comment by tristanlabelle** [comment]
One interesting bit from [the spec](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) is this:

> A matcher that captures the above warning (and errors) looks like this:
```
{
  // The problem is owned by the cpp language service.
  "owner": "cpp",
```

If the language service can take ownership of problems matched by the problem matcher and subsequently modify them, it might be possible to implement this grouping as a post-processing step. This would also provide a path to not keeping around `swiftc` errors until the next compilation if they match a `sourcekitd` error and the `sourcekitd` error gets fixed.

**Comment by adam-fowler** [comment]
I have no idea how the language client outputs to the problem pane but it won't be with a problem matcher I expect.

I'm not sure I am able to produce an output which could be post processed to group the problems correctly. 

One other thing, it appears sourcekit-lsp doesn't output many of the notes you get from the compiler.

**Comment by ahoppen** [comment]
Just to add a cross-link, the intended solution from the Swift compiler is to read the serialized diagnostics file: https://github.com/swift-server/vscode-swift/issues/670

**Comment by adam-fowler** [comment]
I believe this is resolved now
