### ISSUE TITLE
Fix spaces appearing in DAP terminal output

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#645]
Output from tests includes additional spaces. Investigate where they are coming from.

**Comment by adam-fowler** [comment]
I can't replicate this now, which is frustrating

**Comment by ahoppen** [comment]
I think I saw this as well at some point and believe they aren’t actually spaced. If I remember correctly, if you copy the text, it doesn’t contain a space between all the characters, so it rather appears to be a rendering issue. Not sure if that helps, though.

**Comment by plemarquand** [comment]
@adam-fowler have you seen this since we reworked how swift tasks are run? The Test Results and Debug Console for tests seems to be pretty consistent with what you get just running the tests on the Terminal now.

**Comment by adam-fowler** [comment]
> @adam-fowler have you seen this since we reworked how swift tasks are run? The Test Results and Debug Console for tests seems to be pretty consistent with what you get just running the tests on the Terminal now.

No I haven't but then I haven't been looking for it

**Comment by plemarquand** [comment]
I think the task/terminal work that @matthewbastien and @award999 added may have addressed this. I'll close for now and please reopen this if you see the issue again.
