### ISSUE TITLE
Show diff output for failed `XCTAssertEqual` calls

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#654]
When an `XCTAssertEqual` fails, it would be great if we could see a diff of the actual vs expected output. That would make spotting the actual difference a lot easier.

**Comment by adam-fowler** [comment]
It's doing it for me
<img width="814" alt="Screenshot 2023-12-05 at 17 57 32" src="https://github.com/swift-server/vscode-swift/assets/9382567/2f73c450-5131-4f1b-b159-439da847f9ca">

**Comment by ahoppen** [comment]
Oh, sorry, I should have been clearer. It would be nice if the extension could show an actual diff between the expected and the actual value.

For example for

```swift
XCTAssertEqual("hello world", "hello, world")
```

It would be nice if the extension could open a diff view that highlights the `,`. Or, even simpler if it reformatted the output to multiple lines. 

```
XCTAssertEqual failed: 
+ hello world
- hello, world
```

For context, the sourcekit-lsp repo has a number of test cases where we are comparing arrays with multiple elements and if these tests fail, I usually take the `XCTAssertEqual` output and format it on two lines like above to determine where the actual difference is.
