### ISSUE TITLE
Investigate new Test Coverage API from VSCode

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#677]
This is now released in VSCode v1.88
https://code.visualstudio.com/api/extension-guides/testing#test-coverage

**Comment by daveyc123** [comment]
@adam-fowler What are your thoughts on bumping the engine version?

**Comment by plemarquand** [comment]
I can add this to my queue of things to investigate.

**Comment by adam-fowler** [comment]
I'm happy to up the vscode version. It would require people to have VSCode from February (I think). But VSCode pretty much expects you to upgrade every month.

**Comment by daveyc123** [comment]
We're on the same page then. Thanks!
