### ISSUE TITLE
Mark compiler issues as stale if a file is edited

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#750]
When compilation of a file produces errors and those errors, these errors are displayed in the source editor. However, even when the source file has been modified, the issue will linger around until I build again. I’m not sure if it’s possible at all, but I think it would be great if build errors could be marked as stale (eg. gray instead of red) when the source file has been edited. That way, it’s easy to tell which errors are live errors from `sourcekit-lsp` that still need to be addressed and which ones are from a previous build.

**Comment by adam-fowler** [comment]
I have no control over how the problems view is rendered.

**Comment by matthewbastien** [comment]
I can investigate this one to figure out the feasibility.

**Comment by adam-fowler** [comment]
See #759

**Comment by award999** [comment]
I'd love to run with this issue

**Comment by adam-fowler** [comment]
@award999 #759 gives a possible route to solving this.

**Comment by award999** [comment]
Not working
