### ISSUE TITLE
Add a way to run a test multiple times in a row

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#832]
Sometimes, when debugging a non-deterministic test, it is useful if you can run it multiple times in a row until it fails. It would be great if the Swift Extension offered that ability.

**Comment by adam-fowler** [comment]
Using swift-testing you could do that.
```swift
@Test(arguments: 0..<100)
func testMultiple(attempt: Int){
    ...
}
```

**Comment by ahoppen** [comment]
I was thinking XCTest ;-)

**Comment by adam-fowler** [comment]
This seems quite niche. Is there any reason you can't wrap the test in a for loop that runs it multiple times.

**Comment by ahoppen** [comment]
I could. I just found the Xcode feature to run a test repeatedly useful quite regularly because it also gives you a few things out of the box like logging which iteration it’s currently on.

**Comment by plemarquand** [comment]
I've used this a few times in Xcode to diagnose flakey XCTests that have setUp/tearDown

**Comment by adam-fowler** [comment]
I didn't know this was an option in Xcode.

**Comment by award999** [comment]
Verified
