### ISSUE TITLE
Write log messages from SourceKit-LSP’s index log to a separate output view 

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/vscode-swift#833]
https://github.com/apple/sourcekit-lsp/pull/1398 adds an LSP extension to set a `logName` in the `window/logMessage` notifications. It would be great if the VS Code extension could write log messages that have `logName` set to an output view with that name. This would ensure that the index log does not get interleaved with other logs from SourceKit-LSP such as stderr messages or the message trace if verbose logging is enabled in the Swift extension.

**Comment by adam-fowler** [comment]
The logging of LSP output is internal to the VSCode language client. We don't have control over this. I checked to see if we could catch log messages via a middleware but that doesn't seem possible either.

**Comment by ahoppen** [comment]
I think @award999 had some ideas of how to capture the log output.

**Comment by award999** [comment]
Ya we can't hook into the middleware but should be able to set an notification handler, I'll take a look next week and make sure works as I expect it to

**Comment by award999** [comment]
For verification need to enable background indexing https://github.com/apple/sourcekit-lsp/blob/main/Documentation/Enable%20Experimental%20Background%20Indexing.md

**Comment by matthewbastien** [comment]
Verified with e8308d6
