### ISSUE TITLE
Need to reload vscode to start swift-lldb debug session

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#848]
**Describe the bug**
Need to reload vscode to start swift-lldb debug session when enabling swift.debugger.useDebugAdapterFromToolchain setting

<img width="271" alt="Screenshot 2024-06-05 at 4 05 03 PM" src="https://github.com/swift-server/vscode-swift/assets/78549403/e62a97a6-894c-448c-8f84-a1d15eeab847">

**To Reproduce**
1. Set swift.debugger.path to lldb-dap path
2. Enable the  swift.debugger.useDebugAdapterFromToolchain 
3. When prompted select to "Update" generated launch configurations

**Expected behavior**
Should be able to run this debug session with restarting vscode

**Environment**
 - OS: [e.g. Ubuntu 20.04] macOS 
 - Swift version (output of `swift --version`) 6.0 snapshot
 - Visual Studio Code version: 
 - vscode-swift version:

**Additional context**

**Comment by matthewbastien** [comment]
Verified with e8308d6
