### ISSUE TITLE
Run tests using the release configuration

### ISSUE THREAD

**Issue by fumoboy007** [swiftlang/vscode-swift#849]
**Is your feature request related to a problem? Please describe.**
I need to be able to run tests using the release configuration for extra performance and production readiness.

**Describe the solution you'd like**
As far as I can tell, the Test Explorer always chooses the debug executable. I want a toggle somewhere to build and run the tests using the release configuration.

**Describe alternatives you've considered**
I don’t see an alternative aside from directly using a shell.

**Comment by adam-fowler** [comment]
We could probably add a test profile for running tests in release. @plemarquand what do you think?

**Comment by fumoboy007** [comment]
Thanks so much for your consideration!

I forgot to say that I also need to be able to debug the test in release mode. My current use case is that I am debugging a test failure for my Swift package that only happens on Linux and only in release mode. 😄

**Comment by plemarquand** [comment]
@fumoboy007 Sounds good, the way to access these when they're added will be to right click a test and then pick one of:

- Execute Using Profile... > Run Test (Release Mode)
- Execute Using Profile... > Debug Test (Release Mode)

**Comment by plemarquand** [comment]
Draft is up in #856

**Comment by award999** [comment]
Verified with b461f8f
