### ISSUE TITLE
Reorder running of tests through debugger

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#852]
Currently we do the following (as I understand)
- create a pipe
- If there are swift-testing tests create a test config
- If there are xctest tests create a test config
- build tests (via preLaunchTask)
- run tests
- delete pipe

Perhaps it should be
- build tests
- If there are swift-testing tests create a test config and pipe
- If there are xctest tests create a test config
- run tests
- delete pipe if it exists

**Comment by plemarquand** [comment]
After some changes in other PRs I feel like the current debugging flow matches the proposed one. Let me know if you'd like me to make some changes related to this, but for now I'll close this out.

**Comment by adam-fowler** [comment]
> After some changes in other PRs I feel like the current debugging flow matches the proposed one. Let me know if you'd like me to make some changes related to this, but for now I'll close this out.

Are we certain we are only creating a pipe when we need it?

**Comment by plemarquand** [comment]
Good call, I did find that we're creating the pipe when there are no swift-testing tests when debugging.

**Comment by award999** [comment]
Verified with e548b63188333a84ade036e183a2b90656d64b4f
