### ISSUE TITLE
Don't include swift-latest symbolic link in available toolchains

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#865]
When you install a swift snapshot toolchain on macOS it setups up a `swift-latest.xctoolchain` symbolic link to point to it. We shouldn't include this symbolic link in the list of toolchains available when displaying the `Select toolchain...` menu

**Comment by matthewbastien** [comment]
Is there a reason you want to remove it? I feel like it's useful for people who always want to point their VSCode at the latest public Swift toolchain that they've downloaded.

**Comment by adam-fowler** [comment]
If we are going to keep it we should change the menu item to be `Latest Installed Toolchain`, or something similar, and verify the toolchain it is pointing to exists
