### ISSUE TITLE
Making changes in products does not reflect into other products.

### ISSUE THREAD

**Issue by muchitto** [swiftlang/vscode-swift#906]
**Describe the bug**
When a product depends on another product in the same project, it seems when making changes in the product (in this case the Library product/target), it does not reflect instantly in the executable product/target.

**To Reproduce**

1. Create file structure as follows:
```
Sources/
    Library/
        Library.swift
    swift-error-test/
        main.swift
Package.swift
```

2. Add these files:

`Library.swift`:

```swift
public func libraryTest(thing: String) {
}
```

`main.swift`:

```swift
import Library

libraryTest(thing: "test")
```

`Package.swift`:
```swift
import PackageDescription

let package = Package(
  name: "swift-error-test",
  products: [
    .executable(name: "swift-error-test", targets: ["swift-error-test"]),
    .library(name: "Library", targets: ["Library"]),
  ],
  targets: [
    .executableTarget(
      name: "swift-error-test",
      dependencies: [
        "Library"
      ]
    ),
    .target(name: "Library"),
  ]
)
```

3. Change something in `Library.swift`, change the name of the function or argument name.

I have to rebuild from command line and restart the the editor for the changes to be reflected.

**Expected behavior**
Changes are instantly reflected.

**Environment**
 - OS: MacOS Sonoma 14.5
 - Swift version: 5.10
 - Visual Studio Code version: 1.90.1
 - vscode-swift version: v1.10.1

**Comment by adam-fowler** [comment]
You need to rebuild at the moment for the index to be updated. There is work going on in SourceKit-LSP to enable background indexing, which will hopefully be available in Swift 6
