### ISSUE TITLE
Swift terminal profile

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#914]
**Is your feature request related to a problem? Please describe.**
I've made the mistake a few times where I have select a toolchain in vscode and it has been built for via tasks. I then go to the integrated vscode terminal to issue to run some swift command that is a different version of swift.

**Describe the solution you'd like**
You can provide different terminal profiles https://code.visualstudio.com/api/references/vscode-api#TerminalProfileProvider so we could provide a Swift terminal profile with selected toolchain in the PATH so that user can select this swift profile in settings, for example `terminal.integrated.defaultProfile.osx`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by matthewbastien** [comment]
There's also the option of just adding to the terminal environment directly using the `ExtensionContext`:

```typescript
context.environmentVariableCollection.clear();
context.environmentVariableCollection.prepend(
    "PATH",
    "/path/to/usr/bin:",
    { applyAtShellIntegration: true }
);
for (const variable in configuration.swiftEnvironmentVariables) {
    context.environmentVariableCollection.replace(
        variable,
        configuration.swiftEnvironmentVariables[variable],
        { applyAtShellIntegration: true }
    );
}
```

Using this approach the user will have the environment automatically populated in their VS Code terminal without having to launch a special profile. The only minor annoyance being that modifying certain variables (e.g. `PATH`) triggers a warning before the terminal will be updated:

<img width="522" alt="Screenshot 2024-06-27 at 2 30 02 PM" src="https://github.com/swiftlang/vscode-swift/assets/65295938/1bd08676-6cd5-413e-a334-28321f1c8bcc">

**Comment by adam-fowler** [comment]
@matthewbastien so that appears every time you start up a terminal window or only for existing terminal windows?

**Comment by matthewbastien** [comment]
@adam-fowler the warning will only appear for existing terminal windows that need to be reloaded to capture new environment variables.

**Comment by award999** [comment]
@matthewbastien if I disable `swift.enableTerminalEnvironment` and then create a new terminal with the swift profile, `swift.swiftEnvironmentVariables` values are added but `which swift` still indicates `/usr/bin/swift` is being used not the selected toolchain path.
