### ISSUE TITLE
XCTest failures showing up under problems view

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#925]
**Describe the bug**
The failure message and location for an XCTest

![Screenshot 2024-06-21 at 9 46 07 AM](https://github.com/swiftlang/vscode-swift/assets/78549403/bf5dafde-cde9-4163-847c-9a85c8533b10)

**To Reproduce**
1. Run a failing XCTest
2. Notice failure shows up under problems view

**Expected behavior**
Only show build failures

**Comment by plemarquand** [comment]
Verified in 0fd61ee584eca15105b3eae62f5b5709bb6b84d5
