### ISSUE TITLE
Unable to format Swift sources

### ISSUE THREAD

**Issue by tonyarnold** [swiftlang/vscode-swift#940]
When running the "Format Document" command, I get the following error: "There is no formatter for swift files installed".

![CleanShot 2024-06-27 at 16 23 01@2x](https://github.com/swiftlang/vscode-swift/assets/4802/6a570cf1-d9bb-4e67-adca-66adac42d844)

I have Xcode 16 beta 2 set as my Swift toolchain.

**Environment**
 - OS: macOS 14.5
 - Swift version swift-driver version: 1.110 Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
 - Visual Studio Code version: 1.90.2
 - vscode-swift version: v1.10.3

**Comment by adam-fowler** [comment]
Go to the settings and type the following in the filter bar `@id:editor.defaultFormatter @lang:swift`. The setting that comes up should be set to Swift. VSCode normally comes up with a dialog if no formatter is chosen, don't know why that didn't appear

**Comment by tonyarnold** [comment]
I just followed those instructions, and it still does the same thing. It added the following lines to my settings.json:

```json
"[swift]": {
  "editor.defaultFormatter": "sswg.swift-lang"
}
```

**Comment by adam-fowler** [comment]
ok, working fine for me, but I'm using a nightly build of swift `swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-22-a.xctoolchain/`. It should work for Xcode beta builds as well. 

If you look in <Xcode install directory>/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin do you see swift-format?

**Comment by tonyarnold** [comment]
Yeah, it's definitely there: 

```
.rwxr-xr-x@ 21M tonyarnold 26 Jun 07:19  /Applications/Xcode-16.0.0-Beta.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-format
```

**Comment by tonyarnold** [comment]
Oh hang on, this is an LSP issue: 

```
[Error - 20:28:54] SourceKit Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error: Unknown option '--experimental-feature'
Usage: source-kit-lsp <options> <subcommand>
  See 'source-kit-lsp --help' for more information.
[Error - 20:28:54] Server process exited with code 64.
[Error - 20:28:54] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

I tried to follow the guide here: https://github.com/apple/sourcekit-lsp/blob/main/Documentation/Enable%20Experimental%20Background%20Indexing.md

**Comment by adam-fowler** [comment]
Ah if LSP doesn't start then you won't get formatting via the swift extension. You should report those issues setting up background indexing on the SourceKit-LSP repo
