### ISSUE TITLE
BUG: #Preview gets flagged as an error (plugin for module 'PreviewsMacros' not found)

### ISSUE THREAD

**Issue by davidalejandroaguilar** [swiftlang/vscode-swift#943]
Feel free to dismiss if this only happens in beta, but would be great if someone has encountered this already (no open issues about this).

Also, if it can't be fixed, wondering if there's a way to tell the extension to ignore it.

On:

* macOS Beta 15.0
* Xcode 16.0 beta 2
* VS Code Version: 1.90.2 (Universal)
* Extension v1.10.3

With this code:

```swift
// Error here
#Preview {
  ContentView()
}
```

Getting error:

```
External macro implementation type 'PreviewsMacros.SwiftUIView' could not be found for macro 'Preview(_:body:)'; plugin for module 'PreviewsMacros' not foundSourceKit
ContentView.swift(126, 1): 'Preview(_:body:)' declared here (SwiftUI.Preview)
```

VSCode settings:

```
  "[swift]": {
    "editor.defaultFormatter": "vknabel.vscode-swiftformat"
    // Also tried with:
    // "editor.defaultFormatter": "sswg.swift-lang"
  },
  "swift.path": "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin"
```

<img width="1143" alt="image" src="https://github.com/swiftlang/vscode-swift/assets/15317732/738cb28b-bc72-479a-b232-6c332abd9931">

**Comment by adam-fowler** [comment]
These macros don't exist in VSCode so not much we can do here. Does wrapping as follows work
```swift
#if canImport(PreviewMacros)
#Preview {
  ContentView()
}
#endif               
```

**Comment by davidalejandroaguilar** [comment]
Thanks for taking a look at this @plemarquand, appreciate your time.

I tried to get a full diagnostic but got this error `Error: Unknown option '--bundle-output-path'`:

```
Unable to capture diagnostic logs: Error: Command failed: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp diagnose --bundle-output-path /var/folders/l2/q76ntgmn4wb0nvrpc97yl1xr0000gn/T/vscode-diagnostics-2024-07-10T00-00-24+03-00/sourcekit-lsp --toolchain /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr Error: Unknown option '--bundle-output-path' Usage: source-kit-lsp diagnose [--os-log-history <os-log-history>] [--toolchain <toolchain>] [--components <components> ...] See 'source-kit-lsp diagnose --help' for more information.
```

The minimal diagnostics files are very small:

[vscode-diagnostics-2024-07-10T00-00-55+03-00.zip](https://github.com/user-attachments/files/16150484/vscode-diagnostics-2024-07-10T00-00-55%2B03-00.zip)

**Comment by davidalejandroaguilar** [comment]
Also, wrapping it in `#if canImport(PreviewMacros)` works to ignore this issue's error!

**Comment by davidalejandroaguilar** [comment]
Ahh damn, but wrapping it in `#if canImport(PreviewMacros)` breaks the preview in XCode... sad.
