### ISSUE TITLE
Unable to detect ML model in scope

### ISSUE THREAD

**Issue by davidalejandroaguilar** [swiftlang/vscode-swift#946]
Feel free to dismiss if this only happens in beta, but would be great if someone has encountered this already (no open issues about this).

Also, if it can't be fixed, wondering if there's a way to tell the extension to ignore it.

**Describe the bug**
A model that has been created in Xcode and drag and dropped into the project structure, then referenced in the code, gets displayed as not in scope, while Xcode has no error.

### VSCode
<img width="890" alt="image" src="https://github.com/swiftlang/vscode-swift/assets/15317732/d43bb0f9-ef1b-4499-834b-fd72ee7911a6">

### Xcode
<img width="639" alt="image" src="https://github.com/swiftlang/vscode-swift/assets/15317732/308390f6-89aa-44d0-a9d6-b259d8e2b091">

**To Reproduce**
1. Create a ML model in Create ML
2. Drag and drop it into Xcode (within the project folder)
3. Reference it in code
4. Build the app
5. Xcode has no problems
6. VSCode complains about it not being in scope

**Expected behavior**
The model being in scope when used in code.

**Environment**
 - OS: Version 15.0 Beta (24A5279h)
 - Swift version

Have this in my VSCode settings:

```
"swift.path": "/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin"
```

So version is:

```
Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -v
Apple Swift version 6.0 (swiftlang-6.0.0.4.52 clang-1600.0.21.1.3)
Target: arm64-apple-macosx15.0
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-help intro

Welcome to Swift!
```

 - Visual Studio Code version: Version: 1.90.2 (Universal)
 - vscode-swift version: v1.10.3
 - Xcode version: 15.0 Beta (24A5279h)

**Comment by machineko** [comment]
You need to generate swift coreml code file for that, it is not Swift or VScode extension bug.
Something like that
```fish
xcrun coremlc generate swift model.mlmodel outputDirectory
```
And then you also need to precompile it and process within your Package file.

**Comment by award999** [comment]
@davidalejandroaguilar doesn't seem like an extension issue, please re-open if you feel the extension still could be doing something better
