### ISSUE TITLE
launch configurations change / to \ on Windows

### ISSUE THREAD

**Issue by dschaefer2** [swiftlang/vscode-swift#958]
I created a project on my Mac and then checked it out on my Windows machine. VSCode-Swift changed the paths in the launch configurations to be Windows paths. Going back and forth between the platforms is going to be painful.

e.g.
```
    "program": "${workspaceFolder:doug-proj}\\.build\\debug\\doug-proj",
```

Windows does understand the forward slashes.

**Comment by plemarquand** [comment]
Verified in be8372e8cd00a036bbaa5ee90c5b22c34ae37665
