### ISSUE TITLE
In Test Results pane display text associated with individual test

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/vscode-swift#981]
In the Test Results screen you can expand a test run to see all the test cases that were run. When you click on one of these test cases the Test Results screen reports `The test case did not report any output.` Can we associated the output from individual test cases with their test case so we get some output here.

**Comment by plemarquand** [comment]
Fixed in #985

**Comment by award999** [comment]
Verified with d6c91dd379abd6a402dddb3503e35fd328c6ce21
