### ISSUE TITLE
Rename symbol offers the whole function signature, not a symbol

### ISSUE THREAD

**Issue by timsneath** [swiftlang/vscode-swift#989]
**Describe the bug**
Given the below function signature:
![image](https://github.com/user-attachments/assets/52557198-ba25-4cd0-a79f-b42c2de081b0)

I should be able to rename just one of the parameters with the Rename Symbol command, and have the change propogate throughout the system. Instead, I get prompted to rename the entire function. This is contrary to how other languages work in VSCode, where the rename symbol command is focused on a single symbol.

I'd instead expect to be able to just rename "message", without making changes inline to the full function signature.

**Environment**
 - OS: [e.g. Ubuntu 20.04]: 15.0 Beta (24A5298h)
 - Swift version (output of `swift --version`): swift-driver version: 1.112.3 Apple Swift version 6.0 (swiftlang-6.0.0.6.8 clang-1600.0.23.1)
 - Visual Studio Code version: Version: 1.91.1 (Universal)
 - vscode-swift version: v1.10.6

**Comment by adam-fowler** [comment]
This is how it has been implemented in sourcekit-lsp. VSCode has no control over this.
