### ISSUE TITLE
Build All tasks build progress not showing in the status bar

### ISSUE THREAD

**Issue by award999** [swiftlang/vscode-swift#999]
Build All tasks run before debugging a test, or when SourceKit-LSP is disabled and vscode-swift extension is trying to discover tests. For some reason the events on SwiftExecution for onWrite and onClose are not firing so the progress is never shown in the status bar. The onClose issue was worked around with https://github.com/swiftlang/vscode-swift/pull/998

**Comment by adam-fowler** [comment]
This is working fine for Swift 5.10 and VSCode 1.92.0

**Comment by award999** [comment]
I tested it with 5.10 and I still see, so not sure what the issue is. @plemarquand have you seen or maybe this is something weird just with my machine?

**Comment by plemarquand** [comment]
I'm trying with 6.0 and seeing the build all progress in the status bar as expected.

**Comment by award999** [comment]
I just updated to 1.92.1 and no longer see this, I'll close this
